In [5]:
import numpy as np
arr = np.arange(11,20)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
---------NUMPY INDEXING AND SLICING OF VECTORS-----------

In [6]:
arr[5]

np.int64(16)

In [10]:
arr1=arr[1:8:2]
arr1

array([12, 14, 16, 18])

In [16]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [18]:
arr[5]

array([26, 27, 28, 29, 30])

In [19]:
arr[1,2]

np.int64(8)

In [21]:
arr[0,4]

np.int64(5)

In [31]:
arr[3:5,2:4]

array([[18, 19],
       [23, 24]])

In [33]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [34]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [37]:
arr[:,2:3]

array([[ 3],
       [ 8],
       [13],
       [18],
       [23],
       [28]])

In [ ]:
---------------BOOLEAN INDEX------------------------------

In [38]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [39]:
bi = arr%2==0
bi

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True])

In [40]:
arr = arr[bi]
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])