In [ ]:
--------------------ARITHMETIC OPERATIONN----------------------------------

In [6]:
import numpy as np
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

In [7]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [8]:
a1-a2

array([-5, -5, -5, -5, -5])

In [10]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [11]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [12]:
a1//a2

array([0, 0, 0, 0, 0])

In [13]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

In [ ]:
------------BROADCASTING-------------------------

In [15]:
l=[10,20,30,40]
arr=np.array(l)
arr+10

array([20, 30, 40, 50])

In [ ]:
-----------------SHALLOW COPY-------------

In [16]:
a=np.arange(1,11)
arr=a[:5]
arr=arr*10

In [17]:
arr

array([10, 20, 30, 40, 50])

In [18]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
--------------------------DEEP COPY-----------------------------

In [21]:
b=np.arange(1,11)
c=b
c[0]=34

In [22]:
c

array([34,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
b

array([34,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
-----------------shallow copy-------------------

In [48]:
b=np.arange(1,11)
d=b.copy()
d[0]=34

In [49]:
d

array([34,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
---------------ARRAY STACKING---------------------

In [51]:
v1=np.arange(1,5)
v2=np.arange(5,9)

In [52]:
v1

array([1, 2, 3, 4])

In [53]:
v2

array([5, 6, 7, 8])

In [55]:
np.vstack((v1,v2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [57]:
np.hstack((v1,v2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [58]:
np.column_stack((v1,v2))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [59]:
np.row_stack((v1,v2))

C:\Users\khush\AppData\Local\Temp\ipykernel_26600\4256335876.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((v1,v2))


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])