In [ ]:
-------------------------ARRAY CREATION--------------------------

In [1]:
import numpy as np

In [4]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [6]:
l1=[1,2,3.5,"Hello"]
arr2=np.array(l1)
arr2

array(['1', '2', '3.5', 'Hello'], dtype='<U32')

In [8]:
l3=[[1,2,3],[4,5,6],[7,8,9]]
arr3=np.array(l3)
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
-------------------------ARRAY GENERATION FUNCTION----------------------

In [11]:
arr4=np.arange(1,11)
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arr5=np.arange(1,11,2)
arr5

array([1, 3, 5, 7, 9])

In [13]:
arr6=np.zeros(6)
arr6

array([0., 0., 0., 0., 0., 0.])

In [14]:
arr7=np.zeros((3,4))
arr7

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
arr8=np.linspace(1,10,5)
arr8

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
----------------RANDOM GENERATION FUNCTION-----------------

In [41]:
arr9=np.random.rand(6)
arr9

array([0.19425796, 0.99056343, 0.53783946, 0.01102218, 0.81092157,
       0.69325818])

In [36]:
arr10=np.random.randn(6)
arr10

array([ 1.54356746,  0.85185841, -0.74717157,  0.47233188, -0.25139182,
        1.48320367])

In [37]:
arr11=np.random.randint(6)
arr11

4

In [38]:
arr12=np.random.randint(10,20,10)
arr12

array([16, 18, 13, 15, 15, 19, 16, 18, 12, 17], dtype=int32)

In [ ]:
              ------------ARRAY ATTRIBUTES----------------

In [42]:
l4=[[1,2,3],[4,5,6],[7,8,9]]
arr13=np.array(l4)
arr13

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
arr13.shape

(3, 3)

In [44]:
arr13.size

9

In [45]:
arr13.dtype

dtype('int64')

In [ ]:
----------------------ARRAY METHODS-----------------------

In [47]:
arr13.min()

np.int64(1)

In [48]:
arr13.max()

np.int64(9)

In [50]:
arr13.sum()

np.int64(45)

In [51]:
np.sum(arr13,axis=0)

array([12, 15, 18])

In [52]:
np.sum(arr13,axis=1)

array([ 6, 15, 24])

In [53]:
arr13.mean()

np.float64(5.0)

In [54]:
arr13.std()

np.float64(2.581988897471611)

In [55]:
arr13.argmax()

np.int64(8)

In [56]:
arr13.argmin()

np.int64(0)

In [ ]:
-------------------RESHAPING AND RESIZING------------------------

In [60]:
arr14=np.arange(1,31)
arr14

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [61]:
arr14.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [63]:
arr14 = arr14.reshape(5,6) #RESHAPE(JUST STORE RESHAPE FUNCTION IN SAME ARRAY)