In [228]:
import numpy as np

In [229]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [230]:
r=np.sum(s,axis=1)
c=np.sum(s,axis=0)

In [231]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n=s[i:i+3,j:j+3]

In [232]:
a=np.all(r == 45)
b=np.all(c == 45)
d=n.sum()

In [233]:
print((a and b and d) == 45)

True


In [234]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],  # Student 1
    [19, 92, 88],  # Student 2
    [17, 76, 95],  # Student 3
    [18, 65, 70],  # Student 4
    [20, 90, 85]   # Student 5
])

In [235]:
#get shape of matrix
data.shape

(5, 3)

In [236]:
#find average age
print(np.mean(data[:,0]))

18.4


In [237]:
#extract math marks
data[:,1]

array([85, 92, 76, 65, 90])

In [238]:
#find highest science marrks
print(np.max(data[:]))

95


In [239]:
#get detail of student who scored more than 90 in Maths
data[data[:,1]>90]

array([[19, 92, 88]])

In [240]:
#increase maths marks by 5
data[:,1]+=5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [241]:
#how many student younger than 19
len(data[data[:,0]<19])

3

In [242]:
#column wise average
np.mean(data[:,1:],axis=0)

array([86.6, 83.2])

In [243]:
# Details of students who scored at least 80 marks in both subjects
data[(data[:,1:] > 79).all(axis=1)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [246]:
#replace all marks of science <75 with 0
data[:, 2][data[:, 2] < 75] = 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])